name: Slamcore Python bindings CI

on: push

env:
  PACKAGE_NAME: slamcore-dev
  PACKAGE_VERSION: 23.01.48
  DATASET: minimal

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{matrix.os}}

    outputs:
      WHEEL_NAME_bionic: ${{ steps.build-wheel.outputs.WHEEL_NAME_bionic }}
      WHEEL_NAME_focal: ${{ steps.build-wheel.outputs.WHEEL_NAME_focal }}

    steps:
    - name: Checkout Slamcore Python bindings
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install ninja-build libeigen3-dev && python3 -m pip install setuptools "pybind11[global]" mypy numpy wheel

    - name: Get OS codename
      run: echo "OS_CODENAME=$(lsb_release --codename | cut -f2)" >> $GITHUB_ENV

    - name: Download Slamcore Dev package
      uses: slamcore/s3-cp-action@v2
      with:
        aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        source: s3://slamcore-python/signed_packages/${{env.PACKAGE_NAME}}_${{env.PACKAGE_VERSION}}-${{env.OS_CODENAME}}1_github_amd64.deb
        dest: deps/${{env.PACKAGE_NAME}}_${{env.PACKAGE_VERSION}}-${{env.OS_CODENAME}}1_github_amd64.deb

    - name: Install Slamcore Dev package
      run: sudo apt install ./deps/${{env.PACKAGE_NAME}}_${{env.PACKAGE_VERSION}}-${{env.OS_CODENAME}}1_github_amd64.deb

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -GNinja

    - name: Build library
      run: cd ${{github.workspace}}/build && ninja slamcore_python -v

    - name: Build wheel
      id: build-wheel
      run: |
         cd ${{github.workspace}}/build && ninja slamcore_python_wheel -v
         WHEEL_NAME=$(basename ${{github.workspace}}/build/python/*.whl)
         echo "WHEEL_NAME_${{env.OS_CODENAME}}=${WHEEL_NAME}" >> $GITHUB_OUTPUT
         echo "WHEEL_NAME=${WHEEL_NAME}" >> $GITHUB_ENV

    - name: Install wheel package
      working-directory: ${{github.workspace}}/build
      run: python3 -m pip install python/*.whl

    - name: Test import Slamcore Python package
      run: python3 -c 'import slamcore'

    - name: Upload Slamcore wheel package
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.WHEEL_NAME}}
        path: ${{github.workspace}}/build/python/*.whl

  tests:
    needs: build

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        test_suite: ["streams", "subsystems", "misc"]

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout Slamcore Python bindings
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install zstd libeigen3-dev && python3 -m pip install numpy pytest

    - name: Get OS codename
      run: echo "OS_CODENAME=$(lsb_release --codename | cut -f2)" >> $GITHUB_ENV

    - name: Download Slamcore Dev package
      uses: slamcore/s3-cp-action@v2
      with:
        aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        source: s3://slamcore-python/signed_packages/${{env.PACKAGE_NAME}}_${{env.PACKAGE_VERSION}}-${{env.OS_CODENAME}}1_github_amd64.deb
        dest: deps/${{env.PACKAGE_NAME}}_${{env.PACKAGE_VERSION}}-${{env.OS_CODENAME}}1_github_amd64.deb

    - name: Install Slamcore Dev package
      run: sudo apt install ./deps/${{env.PACKAGE_NAME}}_${{env.PACKAGE_VERSION}}-${{env.OS_CODENAME}}1_github_amd64.deb

    - name: Get wheel name
      run: |
        WHEEL_NAME_bionic=${{ toJSON(needs.build.outputs.WHEEL_NAME_bionic) }}
        WHEEL_NAME_focal=${{ toJSON(needs.build.outputs.WHEEL_NAME_focal) }}
        echo "WHEEL_NAME=$WHEEL_NAME_${{env.OS_CODENAME}}" >> $GITHUB_ENV

    - name: Download Slamcore wheel package
      uses: actions/download-artifact@v3
      with:
        name: ${{env.WHEEL_NAME}}
        path: ~/downloads

    - name: Install wheel package
      working-directory: ${{github.workspace}}
      run: python3 -m pip install ~/downloads/*.whl

    - name: Download dataset (${{env.DATASET}})
      uses: slamcore/s3-cp-action@v2
      with:
        aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        source: s3://slamcore-python/datasets/${{env.DATASET}}.tar.zst
        dest: downloads/${{env.DATASET}}.tar.zst

    - name: Decompress dataset
      run: mkdir datasets && tar --use-compress-program=unzstd -xvf downloads/${{env.DATASET}}.tar.zst -C datasets

    - name: Run tests
      run: python3 -m pytest -v --dataset datasets/${{env.DATASET}} ${{github.workspace}}/tests/test_${{matrix.test_suite}}.py
